import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, FileText, Menu, MoreHorizontal, Paperclip, Plus, Search, Settings, Tag, Upload, X } from 'lucide-react';
import './styles.css';

const TODAY = '2026-08-26';
function readStored(key, fallback) { try { const raw = localStorage.getItem(key); const value = raw ? JSON.parse(raw) : fallback; return Array.isArray(fallback) ? (Array.isArray(value) ? value : fallback) : value; } catch { return fallback; } }
function normalizeDoc(doc) { return { ...doc, tags: Array.isArray(doc.tags) ? doc.tags : [], attachments: Array.isArray(doc.attachments) ? doc.attachments : [], content: typeof doc.content === 'string' ? doc.content : '', title: doc.title || '未命名便笺' }; }

const seedProjects = [
  { id: 'product', name: '产品迭代', color: '#5f9d95' },
  { id: 'client', name: '客户项目', color: '#b47eb2' },
  { id: 'growth', name: '个人成长', color: '#d79661' },
];
const seedDocs = [
  { id: 1, project: 'product', title: '首页信息架构梳理', content: '# 首页信息架构梳理\n\n> 目标：让用户在 5 秒内理解 DailyTime 能解决什么问题。\n\n## 当前结论\n\n- [x] 明确首屏核心价值\n- [ ] 补充用户场景入口\n- [ ] 与视觉同学确认信息层级\n\n## 需要继续思考\n\n首页不应该只是任务列表，而应该是一个可以持续沉淀工作上下文的地方。\n\n![首页草图](https://images.unsplash.com/photo-1558655146-d09347e92766?w=900)', updated: '今天 09:42', planned: '2026-08-26', plannedTime: '09:42', status: '进行中', tags: ['设计', '本周重点'], attachments: ['首页改版草案.pdf'] },
  { id: 2, project: 'product', title: '用户访谈记录整理', content: '# 用户访谈记录整理\n\n## 访谈对象\n\n- 产品经理 2 位\n- 设计师 3 位\n- 独立开发者 2 位\n\n## 观察\n\n> 大多数人不是缺少待办清单，而是缺少工作上下文的连续记录。', updated: '昨天 18:10', planned: '2026-08-27', plannedTime: '18:10', status: '未开始', tags: ['研究'], attachments: [] },
  { id: 3, project: 'client', title: '周报数据可视化', content: '# 周报数据可视化\n\n## 本周需要交付\n\n- [ ] 统一指标口径\n- [ ] 完成趋势图\n- [ ] 输出可分享版本', updated: '昨天 15:35', planned: '2026-08-26', plannedTime: '15:35', status: '未开始', tags: ['交付', '客户'], attachments: ['数据源.xlsx'] },
  { id: 4, project: 'product', title: '设计评审会纪要', content: '# 设计评审会纪要\n\n## 已达成共识\n\n1. 用工作空间承载上下文。\n2. 用文档而不是卡片承载完整内容。\n3. 时间规划只作为文档属性存在。', updated: '8 月 25 日', planned: '2026-08-25', plannedTime: '10:20', status: '已完成', tags: ['会议'], attachments: [] },
  { id: 5, project: 'growth', title: '阅读《设计的心理学》', content: '# 阅读《设计的心理学》\n\n## 摘录\n\n好的设计应该让复杂的事情变得自然。\n\n## 我的思考\n\n把今天的工作写下来，本身也是在降低未来重新理解它的成本。', updated: '8 月 24 日', planned: '2026-08-28', plannedTime: '20:00', status: '未开始', tags: ['输入'], attachments: [] },
];
function fmtDate(v) { if (!v) return '未规划'; const d = new Date(`${v}T12:00:00`); return `${d.getMonth()+1} 月 ${d.getDate()} 日`; }
function addDays(v, n) { const d = new Date(`${v}T12:00:00`); d.setDate(d.getDate()+n); return d.toISOString().slice(0,10); }
function dayLabel(v) { if (!v) return '未规划'; if (v === TODAY) return '今天'; if (v === addDays(TODAY, 1)) return '明天'; return fmtDate(v); }
function currentSchedule() { const now = new Date(); const date = `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`; const time = `${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`; return { date, time }; }

function md(text) { return text.split('\n').map(line => { const x=line.replace(/!\[([^\]]*)\]\(([^)]+)\)/g,'<img alt="$1" src="$2"/>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>'); if(line.startsWith('# '))return `<h1>${x.slice(2)}</h1>`; if(line.startsWith('## '))return `<h2>${x.slice(3)}</h2>`; if(line.startsWith('> '))return `<blockquote>${x.slice(2)}</blockquote>`; if(line.startsWith('- [x] '))return `<p class="check checked"><span>✓</span>${x.slice(6)}</p>`; if(line.startsWith('- [ ] '))return `<p class="check"><span></span>${x.slice(6)}</p>`; if(line.startsWith('- '))return `<li>${x.slice(2)}</li>`; if(!line.trim())return '<div class="gap"/>'; return `<p>${x}</p>`; }).join(''); }

function App(){
 const [projects,setProjects]=useState(()=>readStored('dt-projects', seedProjects));
 const [docs,setDocs]=useState(()=>readStored('dt-docs', seedDocs).map(normalizeDoc));
 const [project,setProject]=useState('product'); const [view,setView]=useState('notes'); const [selectedId,setSelectedId]=useState(1); const [query,setQuery]=useState(''); const [mode,setMode]=useState('write'); const [month,setMonth]=useState(7); const [newProject,setNewProject]=useState(false); const [draft,setDraft]=useState(''); const [mobile,setMobile]=useState(false); const area=useRef(null);
 useEffect(()=>localStorage.setItem('dt-projects',JSON.stringify(projects)),[projects]); useEffect(()=>localStorage.setItem('dt-docs',JSON.stringify(docs)),[docs]);
 const selected=docs.find(d=>d.id===selectedId&&d.project===project)||docs.find(d=>d.project===project)||docs[0]||null; const projectDocs=useMemo(()=>docs.filter(d=>d.project===project&&(!query||`${d.title} ${d.content} ${d.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))),[docs,project,query]);
 const update=(patch)=>selected&&setDocs(p=>p.map(d=>d.id===selected.id?{...d,...patch,updated:'刚刚'}:d));
 function create(){const schedule=currentSchedule();const d={id:Date.now(),project,title:'未命名便笺',content:'# 未命名便笺\n\n开始记录这项工作的背景、思考和下一步。\n\n## 下一步\n\n- [ ] ',updated:'刚刚',planned:schedule.date,plannedTime:schedule.time,status:'未开始',tags:[],attachments:[]};setDocs(p=>[d,...p]);setSelectedId(d.id);setView('notes');}
 function addProject(){if(!draft.trim())return;const p={id:`p-${Date.now()}`,name:draft.trim(),color:'#8ca69b'};setProjects(x=>[...x,p]);setProject(p.id);setDraft('');setNewProject(false);}
 function upload(e){const fs=[...e.target.files];if(fs.length)update({attachments:[...selected.attachments,...fs.map(f=>`${f.name} · ${Math.ceil(f.size/1024)} KB`)]});}
 function pasteImage(e){const image=[...(e.clipboardData?.items||[])].find(item=>item.type.startsWith('image/'));if(!image)return; e.preventDefault(); const file=image.getAsFile(); const reader=new FileReader(); reader.onload=()=>{const alt=file.name||'pasted-image.png'; const insertion=`\n![${alt}](${reader.result})\n`; const el=area.current; const start=el?.selectionStart??selected.content.length; const end=el?.selectionEnd??start; update({content:selected.content.slice(0,start)+insertion+selected.content.slice(end)});}; reader.readAsDataURL(file); }
 function insert(a,b=''){const el=area.current;if(!el)return;const s=el.selectionStart,e=el.selectionEnd,v=selected.content;update({content:v.slice(0,s)+a+v.slice(s,e)+b+v.slice(e)});requestAnimationFrame(()=>{el.focus();el.setSelectionRange(s+a.length,e+a.length);});}
 return <div className={`app ${mobile?'mobile-open':''}`}>
  <aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span><div><b>DailyTime</b><small>便笺工作台</small></div><button className="mobile-close" onClick={()=>setMobile(false)}><X size={17}/></button></div><button className="new-note" onClick={create}><Plus size={16}/> 新建便笺 <kbd>N</kbd></button><div className="side-title">项目 <button onClick={()=>setNewProject(true)}><Plus size={15}/></button></div><div className="projects">{projects.map(p=><button key={p.id} className={project===p.id?'active':''} onClick={()=>{setProject(p.id);setView('notes');setMobile(false);}}><i style={{background:p.color}}/><span>{p.name}</span><em>{docs.filter(d=>d.project===p.id).length}</em></button>)}</div><div className="side-divider"/><div className="view-links"><button className={view==='notes'?'active':''} onClick={()=>setView('notes')}><FileText size={15}/> 便笺</button><button className={view==='calendar'?'active':''} onClick={()=>setView('calendar')}><CalendarDays size={15}/> 项目日历</button></div><div className="sidebar-foot"><button><Settings size={15}/> 设置</button><div className="profile"><span>H</span><div><b>Huibetter</b><small>我的工作空间</small></div><MoreHorizontal size={16}/></div></div></aside>
  <main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobile(true)}><Menu size={19}/></button><div className="crumb"><span>{projects.find(p=>p.id===project)?.name}</span><span>/</span><b>{view==='notes'?'便笺':'项目日历'}</b></div><div className="top-right"><label className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索便笺"/></label><div className="avatar">H</div></div></header>{view==='notes'?<NotesView {...{projects,project,projectDocs,selected,setSelectedId,create,mode,setMode,area,update,upload,insert}}/>:<Calendar {...{projects,docs,month,setMonth,setProject,setSelectedId,setView}}/>}</main>
  {newProject&&<div className="modal" onMouseDown={()=>setNewProject(false)}><div className="modal-box" onMouseDown={e=>e.stopPropagation()}><div><b>新建项目</b><button onClick={()=>setNewProject(false)}><X size={16}/></button></div><p>项目用于整理一组相关便笺，并在日历中查看安排。</p><input autoFocus value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addProject()} placeholder="例如：年度规划"/><footer><button onClick={()=>setNewProject(false)}>取消</button><button onClick={addProject}>创建项目</button></footer></div></div>}
 </div>
}
function NotesView({projects,project,projectDocs,selected,setSelectedId,create,mode,setMode,area,update,upload,insert}){
 const groups=projectDocs.reduce((all,d)=>{const key=d.planned||'none';(all[key]??=[]).push(d);return all},{});
 const ordered=Object.entries(groups).sort(([a],[b])=>a==='none'?1:b==='none'?-1:b.localeCompare(a));
 ordered.forEach(([,items])=>items.sort((a,b)=>(b.plannedTime||'00:00').localeCompare(a.plannedTime||'00:00')));
 return <div className="notes-layout"><section className="note-list"><div className="list-heading"><div><small>PROJECT NOTES</small><h1>{projects.find(p=>p.id===project)?.name}</h1></div><button onClick={create}><Plus size={16}/></button></div><div className="note-count">{projectDocs.length} 篇便笺 · 按计划日期</div><div className="note-timeline">{ordered.map(([date,items])=><div className="timeline-group" key={date}><div className="timeline-date"><span className="timeline-node"/><b>{date==='none'?'未安排':dayLabel(date)}</b>{date!=='none'&&<small>{date}</small>}</div><div className="timeline-notes">{items.map(d=><button className={`note-item ${selected?.id===d.id?'selected':''}`} key={d.id} onClick={()=>setSelectedId(d.id)}><div><FileText size={14}/><b>{d.title}</b></div><p>{d.content.replace(/[#>*\-\[\]]/g,'').trim().slice(0,65)}</p><small>{d.plannedTime||'未设置时间'} · {d.updated}{d.status==='已完成'&&' · 已完成'}</small></button>)}</div></div>)}</div></section><section className="editor">{selected&&<><div className="editor-head"><span><i style={{background:projects.find(p=>p.id===selected.project)?.color}}/>{projects.find(p=>p.id===selected.project)?.name}</span><div><label><Upload size={14}/> 上传<input type="file" multiple onChange={upload}/></label><button onClick={()=>update({status:selected.status==='已完成'?'未开始':'已完成'})}>{selected.status==='已完成'?<Check size={14}/>:<Clock3 size={14}/>} {selected.status==='已完成'?'已完成':'标记完成'}</button></div></div><div className="format-bar"><button className={mode==='write'?'on':''} onClick={()=>setMode('write')}>编辑</button><button className={mode==='preview'?'on':''} onClick={()=>setMode('preview')}>预览</button><span/><button onClick={()=>insert('## ')}>H2</button><button onClick={()=>insert('**','**')}><b>B</b></button><button onClick={()=>insert('- [ ] ')}>☑</button><button onClick={()=>insert('> ')}>❞</button><button onClick={()=>insert('`','`')}>˂/˃</button></div><div className="paper">{mode==='write'?<textarea ref={area} value={selected.content} onChange={e=>update({content:e.target.value})} onPaste={pasteImage} placeholder="开始写下这项工作的背景、过程和结论……"/>:<div className="preview" dangerouslySetInnerHTML={{__html:md(selected.content)}}/>}<div className="paper-foot"><div>{selected.tags.map(t=><span key={t}><Tag size={10}/>{t}</span>)}<button onClick={()=>update({tags:[...selected.tags,'新标签']})}><Plus size={11}/>标签</button></div><small>{selected.content.length} 字符 · 自动保存</small></div></div></>}</section></div>}
function Calendar({projects,docs,month,setMonth,setProject,setSelectedId,setView}){const year=2026,first=new Date(year,month,1).getDay(),total=new Date(year,month+1,0).getDate(),cells=Array.from({length:first+total},(_,i)=>i<first?null:i-first+1);return <div className="page"><div className="page-head calendar-head"><div><small>PROJECT CALENDAR</small><h1>项目日历</h1><p>每种颜色代表一个项目，点击便笺直接回到编辑。</p></div><div className="month"><button onClick={()=>setMonth(m=>Math.max(0,m-1))}><ChevronLeft size={17}/></button><b>2026 年 {month+1} 月</b><button onClick={()=>setMonth(m=>Math.min(11,m+1))}><ChevronRight size={17}/></button></div></div><div className="legend">{projects.map(p=><span key={p.id}><i style={{background:p.color}}/>{p.name}</span>)}</div><div className="calendar"><div className="weekdays">{['日','一','二','三','四','五','六'].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{cells.map((day,i)=>{const date=day?`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`:'';const items=docs.filter(d=>d.planned===date);return <div className={`cell ${date===TODAY?'today':''}`} key={i}><b>{day}</b>{items.map(d=>{const p=projects.find(x=>x.id===d.project);return <button key={d.id} style={{borderLeftColor:p?.color}} onClick={()=>{setProject(d.project);setSelectedId(d.id);setView('notes')}}><i style={{background:p?.color}}/>{d.title}</button>})}</div>})}</div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);





